variables:
  - name: ascName
    value: WAWS_Container_Images
  
  - name: acrName
    value: wawsimages.azurecr.io
    
  - name: baseImageName
    value: mcr.microsoft.com/oryx
   
parameters:
  baseImageVersion: "20220502.2"
  stackName: ""
  stackVersion : ""
  
jobs:
- steps:
  - task: ComponentGovernanceComponentDetection@0

  - task: ShellScript@2
    displayName: 'Generate Dockerfile and its dependencies'
    inputs:
      scriptPath: $(System.DefaultWorkingDirectory)/v2/src/generate_dockerfiles_for_runtime_images.sh
      args: ${{ parameters.stackName }} $(Build.ArtifactStagingDirectory) ${{ variables.baseImageName }} ${{ parameters.baseImageVersion }} "$(System.DefaultWorkingDirectory)/v2/src/${{ parameters.stackName }}" ${{ parameters.stackVersion }}
  
  - task: Docker@2
    displayName: Logout of ACR
    inputs:
      command: logout
      azureSubscriptionEndpoint: ${{ variables.ascName }}
      azureContainerRegistry: ${{ variables.acrName }}

  - task: Docker@1
    displayName: Container registry login
    inputs:
      command: login
      azureSubscriptionEndpoint: ${{ variables.ascName }}
      azureContainerRegistry: ${{ variables.acrName }}

  - task: ShellScript@2
    displayName: 'Building Image'
    inputs:
      scriptPath: $(System.DefaultWorkingDirectory)/v2/src/build_and_push_runtime_images.sh
      args: $(Build.ArtifactStagingDirectory) appsvctest "$(System.DefaultWorkingDirectory)/v2/src/${{ parameters.stackName }}" $(Build.BuildNumber) ${{ parameters.stackName }} $(Build.Reason) ${{ parameters.stackVersion }}