resources:
- repo: self
  fetchDepth: 15

variables:
- group: AppServiceLinux

jobs:

- job: Job_GenerateDockerFiles
  displayName: Generate DockerFiles
  pool:
    vmImage: ubuntu-16.04
  timeoutInMinutes: 100
  steps:
  - script: |
      echo "##vso[task.setvariable variable=InitialChecks;]true"
      echo "##vso[task.setvariable variable=GenerateDockerFiles;]false"
      echo "##vso[task.setvariable variable=BuildBuildImages;]false"
      echo "##vso[task.setvariable variable=PushBuildImages;]false"
      echo "##vso[task.setvariable variable=PushRuntimeImages;]false"
    displayName: 'Set variables'
  - template: GenerateDockerFiles/dockerFilesGenerateTask.yml

- job: Job_DockerBuildImages
  displayName: Build Images
  pool:
    vmImage: ubuntu-16.04
  timeoutInMinutes: 100
  steps:
  - script: |
      echo "##vso[task.setvariable variable=InitialChecks;]true"
      echo "##vso[task.setvariable variable=GenerateDockerFiles;]true"
      echo "##vso[task.setvariable variable=BuildBuildImages;]false"
      echo "##vso[task.setvariable variable=PushBuildImages;]false"
      echo "##vso[task.setvariable variable=PushRuntimeImages;]false"  
  - template: BuildAndTagImages/buildImageJob.yml
trigger: none
